name: CMake Tests
on: 
  push:

jobs:
  buildTest:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        compiler: [g++, clang]
        language: ['cpp']
      
    steps:

    - name: Update packages
      run: |
        sudo apt-get update
        sudo apt-get install -yq valgrind

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: ./install.sh

    - name: Run Test
      run: ./run.sh

    - name: Test Results
      if: always()
      run: cat ../build/Testing/Temporary/LastTest.log

    - name: Valgrind Test
      run: valgrind ./run.sh

    - name: Valgrind Results
      if: always()
      run: cat ../build/Testing/Temporary/LastTest.log