name: CMake Tests
on: 
  push:

jobs:
  buildTest:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build_type: [RelWithDebInfo]
        compiler: [g++, clang++]
      
    steps:

    - name: Update packages
      run: |
        sudo apt-get update
        sudo apt-get install -yq valgrind

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: ./install_with_args.sh .. ${{matrix.build_type}} ${{matrix.compiler}}

    - name: Run Test
      run: |  
        cd ../build-class
        ctest

    - name: Test Results
      if: always()
      run: cat ../build-class/Testing/Temporary/LastTest.log

    - name: Valgrind Test
      run: |
        cd ../build-class
        valgrind ./test_math

    - name: Valgrind Results
      if: always()
      run: cat ../build-class/Testing/Temporary/LastTest.log