name: CMake Tests
on: 
  push:

jobs:
  buildTest:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build_type: [Release, RelWithDebInfo]
        compiler: [g++]
        language: ['cpp']
      
    steps:

    - name: Update packages
      run: |
        sudo apt-get update
        sudo apt-get install -yq mpich libmpich-dev
        sudo apt-get install -yq valgrind

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build
      run: echo "hello"
  
    # - name: PUMI-PIC Test
    #   run: ctest --test-dir ${{ runner.temp }}/build-pumi-pic

    # - name: PUMI-PIC Print
    #   if: always()
    #   run: cat ${{ runner.temp }}/build-pumi-pic/Testing/Temporary/LastTest.log
